name: check code(Nodejs v18)

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    env: 
      PR_NUMBER: ${{ github.event.number }}
    permissions:
      contents: read
      pull-requests: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: nodejs Setup v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: CI Setup
      run: npm ci

    - name: run reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review # Change reporter.
        eslint_flags: 'src/'
        fail_on_error: 'true'
    - name: run check build
      run: npm run build
    - name: approve
      run: gh pr review $PR_NUMBER --approve